name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b1fdfa23aa66cdddae42ffcd6f6f54a4213915fa74afda1160650fe416e392e"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
