name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f121c6aa413979abfaa26776e84f16e7173b7be6bce51779924d1bd4b70ab05e"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"
