name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e37a179dec6cf50c49d58a91302be528d12ee7b6fd19972c5829e72e76712060"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
