name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c1990df1d3bc8c435ad043b7d1df02c449aa759dbfcad04907defae0317bb50"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
