name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91b3dfba19687885cb2d01146f4950edeeb65665781204a68fba7a0c11acffa8"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"
