name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8403b703631135c4355d8208ef9bbede3277664762b03be7a22f305efc757de4"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
