name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5eb25044164eaa813f47f89709e22cc7490e610cfc7d22a90ff35062922ffd81"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
