name = "Create: Grand Expanse"
author = "Aiz"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d95770adacc03c102b4ca3a51f69db8a068830c00b3fa2f23e8db1d57efead4f"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
