name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2117c843d3909a03771e579a1af7e3ee5587f865699cec0c1fa6d79af5c5e626"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
