name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b5da242ace0cd2861b7dbb4f67361774a54920212fc020fc92cfb607bc6d468"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
