name = "Create: Grand Expanse"
author = "Aiz"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bdc2f6c8dad11415e91e92d99500a70335dbb3f16ea68055f01c92d389791f8"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
