name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d08dc37c40b6df7882e33befad33f49c0b919ebfebb9fa3b4ee6c40c49f5941c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"
