name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4566e2d4aea994e8559874fad2394c46e155a1ee4906d851d59a9ce0d60a989f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"
