name = "Create: Grand Expanse"
author = "Aiz"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23362f8867935340137c3f003a676991f3761cbed5d1124f8eed94c81983bb60"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
no-internal-hashes = true
