name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "744ca6dcf3a6c60dc95fd245b591445a9bf12b65fae9b1774f068c1ace5135fb"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
