name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "841f81eaaceb0e8fac58cf51af8144fa1640832b6f1c66bd2a3312998488abbd"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"
