name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a574227f9ebd8d216a550e2d9e2b49446be312bbfacd5cb0302fc1e517b9186d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"
