name = "Create: Grand Expanse"
author = "Aiz"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57f3c0b99fbdf4ae909c07a2a8d0edcb93d0070436844184440fa2d63e08ac6d"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
