name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cced729f160cdffcb4da1eed8186b57fc79c7e129becb4db9b9ba4a3c00fa1d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"
