name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc2c4e493b3c3f79f5a7330b6cdb86b433dcc8f6cb53666567c134aae979c3bd"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
