name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8cf4329e3746f571cf64f62ac6d39f9cfc08a23f22c6cfe4c327a397dc86481"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"
