name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be886c5c5ad9d06f6eb57e897892dc44f0fb4a66e137ac711168cf26c8a3f132"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
