name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccca578a52022c27b949277f6d5e1dea9185e5156a8e30f05cf790b7218b782a"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
