name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ceb68bcbd2a05da9bb47a07b4d9231dddb5add730954c6066e60aebf62eaa15"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
