name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5116480a41b308834fc560d43dc60ef1dbfa97177a4dea6eda5ae361538903f7"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
