name = "Create Space"
author = "Aiz"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6583367b0d2cd9c544a1d384a3d2bacc5036d83deb440d1e539a6c56287b3643"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.96"
