
#Wires
[wires]
	#Small Connector max output in FE/t (Energy transfer).
	#Range: > 0
    #Default: 1000
	small_connector_max_output = 120
	#Small Connector max input in FE/t (Energy transfer).
	#Range: > 0
    #Default: 1000
	small_connector_max_input = 120
	#Large Connector max input in FE/t (Energy transfer).
	#Range: > 0
    #Default: 5000
	large_connector_max_input = 240
	#Large Connector max output in FE/t (Energy transfer).
	#Range: > 0
    #Default: 5000
	large_connector_max_output = 240


#Make sure config changes are duplicated on both Clients and the Server when running a dedicated Server,
# as the config isnt synced between Clients and Server.
#General Settings
[general]
	#Max stress for the Alternator and Electric Motor (in SU at 256 RPM).
	#Range: > 0
	max_stress = 16384
	#Forge Energy conversion rate (in FE/t at 256 RPM, value is the FE/t generated and consumed is at 256rpm).
	#Range: > 0
	fe_at_max_rpm = 480

#Portable Energy Interface
[portable_energy_interface]
	#PEI max output in FE/t (Energy transfer).
	#Range: > 0
	pei_max_output = 5000
	#PEI max input in FE/t (Energy transfer).
	#Range: > 0
	pei_max_input = 5000

#Electric Motor
[electric_motor]
	#Electric Motor internal capacity in FE.
	#Range: > 0
	motor_capacity = 5000
	#Electric Motor minimum required energy consumption in FE/t.
	#Range: > 0
	motor_min_consumption = 8
	#Electric Motor max input in FE (Energy transfer not consumption).
	#Range: > 0
	motor_max_input = 5000
	#Electric Motor min/max RPM.
	#Range: > 1
	motor_rpm_range = 256

#Tesla Coil
[tesla_coil]
	#Tesla Coil charge rate in FE/t.
	#Range: > 0
	tesla_coil_charge_rate = 5000
	#Tesla Coil fire interval (in ticks).
	#Range: > 0
	tesla_coil_fire_cooldown = 20
	#Hurt range (in blocks/meters).
	#Range: > 0
	tesla_coil_hurt_range = 3
	#Tesla Coil internal capacity in FE.
	#Range: > 0
	tesla_coil_capacity = 40000
	#Energy consumed when Tesla Coil is fired (in FE).
	#Range: > 0
	tesla_coil_hurt_energy_required = 1000
	#Tesla Coil max input in FE/t (Energy transfer).
	#Range: > 0
	tesla_coil_max_input = 10000
	#Tesla Coil charge rate in FE/t for recipes.
	#Range: > 0
	tesla_coil_recipe_charge_rate = 2000


#Alternator
[alternator]
	#Alternator efficiency relative to base conversion rate.
	#Range: 0.01 ~ 1.0
    #Default: 0.75
    #60 FE/t at 256rpm
	generator_efficiency = 0.125
	#Alternator internal capacity in FE.
	#Range: > 0
	generator_capacity = 5000
	#Alternator max input in FE (Energy transfer, not generation).
	#Range: > 0
	generator_max_output = 5000

#Accumulator
[accumulator]
	#Accumulator internal capacity per block in FE.
	#Range: > 0
	accumulator_capacity = 2000000
	#Accumulator max output in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_output = 5000
	#Accumulator max input in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_input = 5000
	#Accumulator max multiblock height.
	#Range: 1 ~ 8
	accumulator_max_height = 5
	#Accumulator max multiblock width.
	#Range: 1 ~ 8
	accumulator_max_width = 3


