
#Gamerules that are set when a world is loaded
[gamerules]
	[gamerules.spawning]
		do_trader_spawning = false
#A collection of misc configs
[misc]
	#If gamerules should be saved to config on world unload
	save_gamerules = false


