name: Continuous Integration

on:
    pull_request:
        branches: [main]

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}
                  # This is important to fetch the changes to the previous commit
                  fetch-depth: 0

            - name: Prettier Check
              # You may pin to the exact commit or the version.
              # uses: rutajdash/prettier-cli-action@d42c4325a3b344f3bd4be482bc34de521998d557
              uses: rutajdash/prettier-cli-action@v1.0.2
              with:
                  # The file pattern to scan
                  file_pattern: # optional, default is **/*.js
                  # The path to the prettierrc file
                  config_path: # optional, default is
                  # The path to the prettierignore file
                  ignore_path: # optional, default is ./.prettierignore
                  # The version of prettier to install
                  prettier_version: # optional, default is latest
                  # Whether the script should fail when linting errors are found
                  fail_on_error: # optional, default is true
